client_config:
  ip_address: "127.0.0.1"
  port: 7497
  client_id: 0

stocks:
  - TSLA
  - NVDA
  - ARM

wsb_to_include: # to change weekly manually
  - NVDA
  - TSLA
  - LUNR
  - DJT
  - PLTR
  - ASTS

todays_date: '20241122'  # we must change this to run the program
cash_to_trade: 35000
number_of_options: -1

start_time_after_nine: 45
minimum_volatility: "65" # annual

buffer_allowed_pennies: 0.05
waiting_time_to_readjust_order: 30

use_wsb: false
