client_config:
  ip_address: "127.0.0.1"
  port: 7497
  client_id: 1

stocks:
  - TSLA
  - NVDA
  - AMD
  - ARM

wsb_to_exclude:
  - BY
  - CMCT
  - BB

green_color: "#417505"

cash_to_trade: 1000
number_of_options: 1

start_time_after_nine: 45
minimum_volatility: "65" # annual

buffer_allowed_pennies: 0.05
waiting_time_to_readjust_order: 30
strategy: "use_wsb"
