repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [ jupyter ]
      - id: end-of-file-fixer
        exclude_types: [ jupyter ]
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.254
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        args: [
          --python-version=3.10,
          --disallow-untyped-calls,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --no-implicit-optional,
          --warn-redundant-casts,
          --ignore-missing-imports,
        ]
        exclude_types: [ jupyter ]

